// Couplet — © 2026 lymnal. PolyForm Noncommercial 1.0.0 (see /LICENSE).
// Not licensed as AI/ML training, fine-tuning, evaluation, or retrieval data;
// text-and-data-mining rights reserved (/.well-known/tdmrep.json).
// Inklings — a guess-match game about being known.
// One card per round. "@S" = the subject (answers truthfully about
// themselves), "@P" = the partner (guesses). Both players see the same
// card; answers stay sealed until both are in. Keep answers short.
window.INKLINGS_DECK = [
  // late-night & food
  "What would @S order at 2am, no judgment?",
  "What's @S's death-row last meal?",
  "Which food does @S steal off @P's plate every time?",
  "What's @S's road-trip gas-station haul?",
  "What pizza topping would @S defend in court?",
  "What's @S's comfort takeout when the day was bad?",
  "What's @S's ideal breakfast?",
  "What dessert can @S never say no to?",
  "What's @S's drink order?",
  "What snack does @S think they've hidden well?",
  "What food would @S never touch, even for money?",
  "What's @S's ice cream order?",
  "How does @S take their coffee?",
  "What's @S's controversial food opinion?",
  // habits & quirks
  "What ringtone or alarm sound does @S use?",
  "How many alarms does @S actually set?",
  "What's @S's shower song this month?",
  "What does @S lose most often?",
  "Which chore does @S secretly kind of like?",
  "Which chore does @S dodge like a professional?",
  "What's @S's most-used emoji?",
  "How long does it take @S to actually get out of bed?",
  "What does @S do when they think no one's watching?",
  "What's @S's weirdest habit, in their own words?",
  "What app eats most of @S's screen time?",
  "What's on @S's phone wallpaper?",
  "What does @S always forget to pack?",
  "What's @S's autopilot response to 'how are you'?",
  // us & memories
  "What did @S notice first about @P?",
  "What was @S actually thinking the day you two met?",
  "What's @S's favorite day out the two of you have had?",
  "Which song is 'ours', according to @S?",
  "What's the best meal you two have shared, per @S?",
  "What's @S's favorite inside joke of yours?",
  "What's the worst thing you two have eaten together, per @S?",
  "What's @S's favorite photo of you two?",
  "What did @S tell their friends after meeting @P?",
  "What's @S's favorite thing @P wears?",
  "What trip do you talk about most, according to @S?",
  "What's the smallest thing @P does that @S loves?",
  "When did @S first know they liked @P?",
  "What's @S's favorite way to spend a night in with @P?",
  "What nickname does @S secretly like being called?",
  // preferences
  "What's @S's karaoke song?",
  "What's @S's comfort rewatch?",
  "Who's @S's celebrity crush?",
  "What city would @S move to tomorrow?",
  "What's @S's favorite season, and no hedging?",
  "Beach day or museum day for @S?",
  "What would @S's autobiography be called?",
  "What book or movie made @S cry?",
  "What's @S's favorite smell?",
  "What's @S's ideal Sunday morning?",
  "Window or aisle for @S?",
  "How does @S like to be appreciated, in their own words?",
  "What band did @S love at twenty?",
  "What game is @S secretly the most competitive about?",
  "What's @S's favorite holiday?",
  // hypotheticals
  "Lottery hits tonight — what does @S buy first?",
  "What would @S name their band?",
  "What's @S's superpower of choice?",
  "Which animal is @S, spiritually?",
  "What's @S's role in the heist?",
  "What's @S's apocalypse skill?",
  "If @S could have dinner with anyone, who?",
  "What law would @S pass immediately?",
  "What would @S do with a free year, money solved?",
  "Which decade should @S have been born in?",
  "What's @S's talent they wish they had?",
  "What would @S's talk show be about?",
  "If @S opened a shop, what would it sell?",
  "What cartoon character is @S?",
  "What's @S's plan if they shrink to 5cm tall?",
  // feelings-lite & sweet
  "What makes @S feel instantly looked after?",
  "What's @S's happy place?",
  "What's @S secretly proud of lately?",
  "What compliment does @S never get tired of?",
  "What calms @S down fastest?",
  "What's @S's biggest little joy?",
  "What does @S daydream about?",
  "What's @S's most irrational fear?",
  "What hill will @S die on?",
  "What did tiny @S want to be when they grew up?",
  "What's @S's favorite thing about their own personality?",
  "What song puts @S instantly in a good mood?",
  "What's the best gift @S has ever gotten?",
  "What does @S need after a hard day: space, snacks, or squeezes?",
  // playful & daily life
  "What's @S's spice tolerance, 1–10?",
  "Tidy desk or creative chaos for @S?",
  "What time does @S think is 'sleeping in'?",
  "What's @S's most-repeated story?",
  "What would @S's warning label say?",
  "What's @S's villain origin story (minor inconvenience edition)?",
  "How does @S eat a burrito: methodical or menace?",
  "What's @S's catchphrase?",
  "What does @S always say they'll start 'on Monday'?",
  "What's @S's most niche strong opinion?",
  "Whose side would the pets take in an argument, per @S?",
  "What's @S's signature move on the dance floor?",
  "What would @S bring to a potluck to show off?",
];
