// Couplet — © 2026 lymnal. PolyForm Noncommercial 1.0.0 (see /LICENSE).
// Not licensed as AI/ML training, fine-tuning, evaluation, or retrieval data;
// text-and-data-mining rights reserved (/.well-known/tdmrep.json).
// Original spectrum cards for Attune (a dial-and-clue mind-reading game).
// "@A" / "@B" render as the two players' names.
window.ATTUNE_SPECTRUMS = [
  ["Freezing", "Sweltering"],
  ["Library quiet", "Concert loud"],
  ["Guilty pleasure", "Proud pleasure"],
  ["Underrated", "Overrated"],
  ["Cheap thrill", "Worth every penny"],
  ["Weekday energy", "Weekend energy"],
  ["Breakfast food", "Midnight snack"],
  ["Cozy", "Glamorous"],
  ["Green flag", "Red flag"],
  ["Small talk", "Deep talk"],
  ["Introvert heaven", "Extrovert heaven"],
  ["Sweet", "Savory"],
  ["Beach day", "Museum day"],
  ["Karaoke song", "Shower song"],
  ["First day", "Ten years in"],
  ["Spontaneous", "Planned to the minute"],
  ["Comfort rewatch", "One-time watch"],
  ["Cat energy", "Dog energy"],
  ["Morning person", "Night owl"],
  ["Overdressed", "Underdressed"],
  ["City mouse", "Country mouse"],
  ["Trendy", "Timeless"],
  ["Texts back instantly", "Leaves you on read"],
  ["Walkable", "Worth the drive"],
  ["Healthy-ish", "Heart attack"],
  ["Travels light", "Three suitcases"],
  ["Icebreaker", "Dealbreaker"],
  ["Podcast person", "Playlist person"],
  ["Rainy day plan", "Sunny day plan"],
  ["Survives the horror movie", "First to go"],
  ["Needs a recipe", "Wings it"],
  ["Group chat famous", "Off the grid"],
  ["Appetizer person", "Dessert person"],
  ["Monday", "Friday"],
  ["Slow burn", "Instant obsession"],
  ["Background noise", "Main character"],
  ["Free", "Priceless"],
  ["Nap", "Espresso"],
  ["Big spoon", "Little spoon"],
  ["Sweet PDA", "Get a room"],
  ["Rom-com", "Action movie"],
  ["Texts in paragraphs", "Texts in fragments"],
  ["Museum gift shop", "Actual museum"],
  ["Hot take", "Universal truth"],
  ["Petty", "Zen"],
  ["Cries at movies", "Made of stone"],
  ["Street food", "Tasting menu"],
  ["Sleeps in", "Up at dawn"],
  ["Trivia night champion", "Charades champion"],
  ["Book smart", "Street smart"],
  ["Overthinks the text", "Sends it immediately"],
  ["Road trip", "Flight"],
  ["Homebody", "Never home"],
  ["Day-two leftovers", "Straight to the trash"],
  ["Pets the stray cat", "Keeps walking"],
  ["Playlist curator", "Shuffle believer"],
  ["Very @A", "Very @B"],
  ["@A would order it", "@B would order it"],
  ["@A's playlist", "@B's playlist"],
  ["Makes @A laugh", "Makes @B laugh"],
  ["@A plans the outing", "@B plans the outing"],
  ["Appetizer", "Dessert"],
  ["Window seat", "Aisle seat"],
  ["Handwritten note", "Voice memo"],
  ["Thrifted", "Brand new"],
  ["Fixes it with tape", "Fixes it with a guy"],
  ["Group chat energy", "Read receipts off"],
  ["Picnic", "Reservation"],
  ["Sunrise", "Sunset"],
  ["Bath person", "Shower person"],
  ["Gas-station find", "Farmers market find"],
  ["Rainy day inside", "Rainy day outside"],
  ["Rewatchable", "Unwatchable"],
  ["Soup weather", "Salad weather"],
  ["Hotel", "Airbnb"],
  ["Front row", "Back row"],
  ["Overpacked", "Forgot socks"],
  ["Board game night", "Video game night"],
  ["Sings the harmony", "Sings the melody wrong"],
  ["Plant parent", "Plant serial killer"],
  ["Human GPS", "Perpetually lost"],
  ["Leftovers gremlin", "Leftovers forgetter"],
  ["Blanket hog", "Furnace"],
  ["Texts a paragraph", "Texts 'k'"],
  ["Handwritten list", "Notes app"],
  ["Spoiler hunter", "Spoiler averse"],
  ["Petty in a fun way", "Forgives instantly"],
  ["Umbrella owner", "Umbrella loser"],
  ["Orders for the table", "Orders last minute"],
  ["Cries at the ad", "Cries at nothing ever"],
  ["Sends memes", "Sends articles"],
  ["Candlelit", "Fluorescent"],
  ["Would pet the stray cat", "Would name the stray cat"],
  ["Bookmarks recipes", "Actually cooks them"],
  ["@A's side of the couch", "@B's side of the couch"],
  ["Something @A would wear", "Something @B would wear"],
  ["@A's camera roll", "@B's camera roll"],
  ["@A before coffee", "@B before coffee"],
  ["A hill @A would die on", "A hill @B would die on"],
  ["@A's dream vacation", "@B's dream vacation"],
];
